POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
    "email": "ninja@gmail.com",
    "password": "123",
    "confirmPassword": "123"
}


###
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "email": "ninja@gmail.com",
    "password": "123"
}

###

GET http://localhost:3001/api/prism/path?path=ngomon/data/foundation/doors/center_entry/left_wall.geojson.json
Content-Type: application/json

###

GET http://localhost:3001/api/bodyComplex/path?path=ngomon/data/foundation/doors/gate_back_left/gate_back_left.json
Content-Type: application/json
###
POST http://localhost:3001/api/prism/saveprism
Content-Type: application/json

{
    "directoryPath": "../GisHistoricalRelicManagement/data/foundation/walls/top_wall"
}

###
POST http://localhost:3001/api/bodyComplex/savebodycomp
Content-Type: application/json

{
    "directoryPath": "../GisHistoricalRelicManagement/data/foundation/doors/gate_right"
}

###
POST http://localhost:3001/api/cylinder/savecylinder
Content-Type: application/json

{
    "directoryPath": "../GisHistoricalRelicManagement/data/secondFloor/column"
}

###
DELETE  http://localhost:3001/api/cylinder/delete?path=ngomon/data/secondFloor/column/columnExtraL.geojson.json

###
DELETE  http://localhost:3001/api/prism/delete?path=ngomon/data/foundation/rails/back_wall/floor.back.wall.rail.wall1.geojson.json

###
DELETE  http://localhost:3001/api/bodyComplex/delete?path=ngomon/data/foundation/doors/gate_right/gate_right_door_top.json




