POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
    "email": "ninja@gmail.com",
    "password": "123",
    "confirmPassword": "123"
}


###
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "email": "ninja@gmail.com",
    "password": "123"
}

###
POST http://localhost:3001/api/prism/saveprism
Content-Type: application/json

{
    "directoryPath": "../GisHistoricalRelicManagement/data/foundation/doors/center_entry"
}


